# Generated by Django 4.2.5 on 2024-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_remove_mailingsettings_time_mailingmessage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Клиенты'),
        ),
    ]
