# Generated by Django 4.2.5 on 2024-01-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailinglog_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='client',
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='client',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Клиент'),
        ),
    ]
